/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */
#ifndef __ADMIN_ALTER_HOST_H__
#define __ADMIN_ALTER_HOST_H__

namespace gpudb
{
    /**
     * A set of parameters for @ref
     * GPUdb::adminAlterHost(const AdminAlterHostRequest&) const
     * "GPUdb::adminAlterHost".
     *
     * Alter properties on an existing host in the cluster. Currently, the only
     * property that can be altered is a hosts ability to accept failover
     * processes.
     */
    struct AdminAlterHostRequest
    {
        /**
         * Constructs an AdminAlterHostRequest object with default parameters.
         */
        AdminAlterHostRequest() :
            host(std::string()),
            options(std::map<std::string, std::string>())
        {
        }

        /**
         * Constructs an AdminAlterHostRequest object with the specified
         * parameters.
         *
         * @param[in] host_  Identifies the host this applies to. Can be the
         *                   host address, or formatted as 'hostN' where N is
         *                   the host number as specified in gpudb.conf
         * @param[in] options_  Optional parameters.
         *                      <ul>
         *                          <li>@ref
         *                              gpudb::admin_alter_host_accepts_failover
         *                              "admin_alter_host_accepts_failover": If
         *                              set to @ref
         *                              gpudb::admin_alter_host_true "true",
         *                              the host will accept processes (ranks,
         *                              graph server, etc.) in the event of a
         *                              failover on another node in the
         *                              cluster.
         *                              Supported values:
         *                              <ul>
         *                                  <li>@ref
         *                                      gpudb::admin_alter_host_true
         *                                      "admin_alter_host_true"
         *                                  <li>@ref
         *                                      gpudb::admin_alter_host_false
         *                                      "admin_alter_host_false"
         *                              </ul>
         *                              The default value is @ref
         *                              gpudb::admin_alter_host_false
         *                              "admin_alter_host_false".
         *                      </ul>
         *                      The default value is an empty map.
         */
        AdminAlterHostRequest(const std::string& host_, const std::map<std::string, std::string>& options_):
            host( host_ ),
            options( options_ )
        {
        }

        /**
         * Identifies the host this applies to. Can be the host address, or
         * formatted as 'hostN' where N is the host number as specified in
         * gpudb.conf
         */
        std::string host;

        /**
         * Optional parameters.
         * <ul>
         *     <li>@ref gpudb::admin_alter_host_accepts_failover
         *         "admin_alter_host_accepts_failover": If set to @ref
         *         gpudb::admin_alter_host_true "true", the host will accept
         *         processes (ranks, graph server, etc.) in the event of a
         *         failover on another node in the cluster.
         *         Supported values:
         *         <ul>
         *             <li>@ref gpudb::admin_alter_host_true
         *                 "admin_alter_host_true"
         *             <li>@ref gpudb::admin_alter_host_false
         *                 "admin_alter_host_false"
         *         </ul>
         *         The default value is @ref gpudb::admin_alter_host_false
         *         "admin_alter_host_false".
         * </ul>
         * The default value is an empty map.
         */
        std::map<std::string, std::string> options;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::AdminAlterHostRequest>
    {
        static void encode(Encoder& e, const gpudb::AdminAlterHostRequest& v)
        {
            ::avro::encode(e, v.host);
            ::avro::encode(e, v.options);
        }

        static void decode(Decoder& d, gpudb::AdminAlterHostRequest& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.host);
                            break;

                        case 1:
                            ::avro::decode(d, v.options);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.host);
                ::avro::decode(d, v.options);
            }
        }
    };
} // end namespace avro

namespace gpudb
{
    /**
     * A set of results returned by @ref
     * GPUdb::adminAlterHost(const AdminAlterHostRequest&) const
     * "GPUdb::adminAlterHost".
     */
    struct AdminAlterHostResponse
    {
        /**
         * Constructs an AdminAlterHostResponse object with default parameters.
         */
        AdminAlterHostResponse() :
            info(std::map<std::string, std::string>())
        {
        }

        /**
         * Additional information.
         */
        std::map<std::string, std::string> info;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::AdminAlterHostResponse>
    {
        static void encode(Encoder& e, const gpudb::AdminAlterHostResponse& v)
        {
            ::avro::encode(e, v.info);
        }

        static void decode(Decoder& d, gpudb::AdminAlterHostResponse& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.info);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.info);
            }
        }
    };
} // end namespace avro

#endif // __ADMIN_ALTER_HOST_H__
