/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */
#ifndef __CHECK_TABLE_H__
#define __CHECK_TABLE_H__

namespace gpudb
{
    /**
     * A set of parameters for @ref
     * GPUdb::checkTable(const CheckTableRequest&) const "GPUdb::checkTable".
     *
     * Scans the requested tables as specified in @ref tableNames for
     * integrity. Any table chunks which fail the check will be marked as
     * corrupt. By default the database will automatically repair corrupt
     * tables (via truncating). Note that since this reads every table column
     * from disk it may be a potentially long-running operation. The option
     * @ref gpudb::check_table_local_only "local_only" can be used to skip any
     * table files already written to a remote storage.
     * Returns table corruption results.
     */
    struct CheckTableRequest
    {
        /**
         * Constructs a CheckTableRequest object with default parameters.
         */
        CheckTableRequest() :
            tableNames(std::vector<std::string>()),
            options(std::map<std::string, std::string>())
        {
        }

        /**
         * Constructs a CheckTableRequest object with the specified parameters.
         *
         * @param[in] tableNames_  List of tables to query. An asterisk returns
         *                         all tables.
         * @param[in] options_  Optional parameters.
         *                      <ul>
         *                          <li>@ref gpudb::check_table_local_only
         *                              "check_table_local_only": If @ref
         *                              gpudb::check_table_true "true" only
         *                              locally persisted files will be
         *                              checked.
         *                              Supported values:
         *                              <ul>
         *                                  <li>@ref gpudb::check_table_true
         *                                      "check_table_true"
         *                                  <li>@ref gpudb::check_table_false
         *                                      "check_table_false"
         *                              </ul>
         *                              The default value is @ref
         *                              gpudb::check_table_false
         *                              "check_table_false".
         *                          <li>@ref gpudb::check_table_show_detail
         *                              "check_table_show_detail": If @ref
         *                              gpudb::check_table_true "true" reports
         *                              individual chunk errors.
         *                              Supported values:
         *                              <ul>
         *                                  <li>@ref gpudb::check_table_true
         *                                      "check_table_true"
         *                                  <li>@ref gpudb::check_table_false
         *                                      "check_table_false"
         *                              </ul>
         *                              The default value is @ref
         *                              gpudb::check_table_true
         *                              "check_table_true".
         *                      </ul>
         *                      The default value is an empty map.
         */
        CheckTableRequest(const std::vector<std::string>& tableNames_, const std::map<std::string, std::string>& options_):
            tableNames( tableNames_ ),
            options( options_ )
        {
        }

        /**
         * List of tables to query. An asterisk returns all tables.
         */
        std::vector<std::string> tableNames;

        /**
         * Optional parameters.
         * <ul>
         *     <li>@ref gpudb::check_table_local_only "check_table_local_only":
         *         If @ref gpudb::check_table_true "true" only locally
         *         persisted files will be checked.
         *         Supported values:
         *         <ul>
         *             <li>@ref gpudb::check_table_true "check_table_true"
         *             <li>@ref gpudb::check_table_false "check_table_false"
         *         </ul>
         *         The default value is @ref gpudb::check_table_false
         *         "check_table_false".
         *     <li>@ref gpudb::check_table_show_detail
         *         "check_table_show_detail": If @ref gpudb::check_table_true
         *         "true" reports individual chunk errors.
         *         Supported values:
         *         <ul>
         *             <li>@ref gpudb::check_table_true "check_table_true"
         *             <li>@ref gpudb::check_table_false "check_table_false"
         *         </ul>
         *         The default value is @ref gpudb::check_table_true
         *         "check_table_true".
         * </ul>
         * The default value is an empty map.
         */
        std::map<std::string, std::string> options;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::CheckTableRequest>
    {
        static void encode(Encoder& e, const gpudb::CheckTableRequest& v)
        {
            ::avro::encode(e, v.tableNames);
            ::avro::encode(e, v.options);
        }

        static void decode(Decoder& d, gpudb::CheckTableRequest& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.tableNames);
                            break;

                        case 1:
                            ::avro::decode(d, v.options);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.tableNames);
                ::avro::decode(d, v.options);
            }
        }
    };
} // end namespace avro

namespace gpudb
{
    /**
     * A set of results returned by @ref
     * GPUdb::checkTable(const CheckTableRequest&) const "GPUdb::checkTable".
     */
    struct CheckTableResponse
    {
        /**
         * Constructs a CheckTableResponse object with default parameters.
         */
        CheckTableResponse() :
            tableNames(std::vector<std::string>()),
            ids(std::vector<std::string>()),
            locations(std::vector<std::string>()),
            errors(std::vector<std::string>()),
            info(std::map<std::string, std::string>())
        {
        }

        /**
         * The names of the tables that were checked.
         */
        std::vector<std::string> tableNames;

        /**
         * The chunk identifiers associated with each reported result.
         */
        std::vector<std::string> ids;

        /**
         * The locations (rank/tom) where each chunk corruption was found.
         */
        std::vector<std::string> locations;

        /**
         * A description of each corruption error detected or count of the
         * errors, based on @ref gpudb::check_table_show_detail "show_detail".
         */
        std::vector<std::string> errors;

        /**
         * Additional information. The default value is an empty map.
         */
        std::map<std::string, std::string> info;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::CheckTableResponse>
    {
        static void encode(Encoder& e, const gpudb::CheckTableResponse& v)
        {
            ::avro::encode(e, v.tableNames);
            ::avro::encode(e, v.ids);
            ::avro::encode(e, v.locations);
            ::avro::encode(e, v.errors);
            ::avro::encode(e, v.info);
        }

        static void decode(Decoder& d, gpudb::CheckTableResponse& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.tableNames);
                            break;

                        case 1:
                            ::avro::decode(d, v.ids);
                            break;

                        case 2:
                            ::avro::decode(d, v.locations);
                            break;

                        case 3:
                            ::avro::decode(d, v.errors);
                            break;

                        case 4:
                            ::avro::decode(d, v.info);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.tableNames);
                ::avro::decode(d, v.ids);
                ::avro::decode(d, v.locations);
                ::avro::decode(d, v.errors);
                ::avro::decode(d, v.info);
            }
        }
    };
} // end namespace avro

#endif // __CHECK_TABLE_H__
