/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */
#ifndef __GET_GRAPH_ENTITIES_H__
#define __GET_GRAPH_ENTITIES_H__

namespace gpudb
{
    /**
     * A set of parameters for @ref
     * GPUdb::getGraphEntities(const GetGraphEntitiesRequest&) const
     * "GPUdb::getGraphEntities".
     *
     * Retrieves node or edge entities from an existing graph, with pagination
     * support via offset and limit. Use @ref
     * GPUdb::showGraph(const ShowGraphRequest&) const "GPUdb::showGraph" to
     * obtain the total number of nodes and edges.
     */
    struct GetGraphEntitiesRequest
    {
        /**
         * Constructs a GetGraphEntitiesRequest object with default parameters.
         */
        GetGraphEntitiesRequest() :
            graphName(std::string()),
            offset(int64_t()),
            limit(int64_t()),
            options(std::map<std::string, std::string>())
        {
        }

        /**
         * Constructs a GetGraphEntitiesRequest object with the specified
         * parameters.
         *
         * @param[in] graphName_  Name of the graph from which to retrieve
         *                        entities.
         * @param[in] offset_  Starting index of the entities to retrieve
         *                     (0-based). The default value is 0.
         * @param[in] limit_  Number of entities to retrieve starting from @a
         *                    offset_. A value of -1 returns all entities from
         *                    the offset to the end. Note: the @ref
         *                    gpudb::GetGraphEntitiesResponse::entitiesInt
         *                    "entitiesInt" or @ref
         *                    gpudb::GetGraphEntitiesResponse::entitiesString
         *                    "entitiesString" array size will be 2x this value
         *                    for nodes (stride 2) or 4x for edges (stride 4).
         *                    The default value is 10000.
         * @param[in] options_  Optional parameters.
         *                      <ul>
         *                          <li>@ref
         *                              gpudb::get_graph_entities_entity_type
         *                              "get_graph_entities_entity_type": The
         *                              type of entity to retrieve.
         *                              Supported values:
         *                              <ul>
         *                                  <li>@ref
         *                                      gpudb::get_graph_entities_edge
         *                                      "get_graph_entities_edge":
         *                                      Retrieve edge entities
         *                                      (default).
         *                                  <li>@ref
         *                                      gpudb::get_graph_entities_node
         *                                      "get_graph_entities_node":
         *                                      Retrieve node entities.
         *                              </ul>
         *                              The default value is @ref
         *                              gpudb::get_graph_entities_edge
         *                              "get_graph_entities_edge".
         *                          <li>@ref
         *                              gpudb::get_graph_entities_server_id
         *                              "get_graph_entities_server_id":
         *                              Indicates which graph server to send
         *                              the request to. Required when the graph
         *                              is distributed across multiple servers.
         *                              The default value is '0'.
         *                          <li>@ref
         *                              gpudb::get_graph_entities_concise_edge_connectivity
         *                              "get_graph_entities_concise_edge_connectivity":
         *                              When true, edges are emitted in a
         *                              compact connectivity form regardless of
         *                              the graph's identifier type: @ref
         *                              gpudb::GetGraphEntitiesResponse::entitiesInt
         *                              "entitiesInt" contains stride-4 records
         *                              [edge_id, node1_index, node2_index,
         *                              edge_label_index] where
         *                              node1_index/node2_index are 0-based
         *                              positions into the node array (obtained
         *                              from a node-entity call on the same
         *                              graph). When requesting nodes with this
         *                              option, the response includes
         *                              tombstoned (deleted) slots in order to
         *                              keep position indices stable so edge
         *                              indices resolve correctly; deleted
         *                              slots carry id=0 for integer graphs or
         *                              an empty identifier for string/WKT
         *                              graphs. For paginated node calls,
         *                              subtract @a offset_ from an edge
         *                              endpoint index to locate it within the
         *                              returned page.
         *                              Supported values:
         *                              <ul>
         *                                  <li>@ref
         *                                      gpudb::get_graph_entities_true
         *                                      "get_graph_entities_true":
         *                                      Compact integer connectivity
         *                                      for edges; deleted node slots
         *                                      included in node output.
         *                                  <li>@ref
         *                                      gpudb::get_graph_entities_false
         *                                      "get_graph_entities_false":
         *                                      Default: edges emit node
         *                                      identifiers (int/string/WKT)
         *                                      matching the graph; deleted
         *                                      nodes are skipped.
         *                              </ul>
         *                              The default value is @ref
         *                              gpudb::get_graph_entities_false
         *                              "get_graph_entities_false".
         *                          <li>@ref
         *                              gpudb::get_graph_entities_include_weights
         *                              "get_graph_entities_include_weights":
         *                              When true and @a options entityType is
         *                              'edge', the response @ref
         *                              gpudb::GetGraphEntitiesResponse::entitiesWeight
         *                              "entitiesWeight" array is populated
         *                              with one float weight per emitted edge
         *                              (aligned 1:1 with the edge records in
         *                              @ref
         *                              gpudb::GetGraphEntitiesResponse::entitiesInt
         *                              "entitiesInt" or @ref
         *                              gpudb::GetGraphEntitiesResponse::entitiesString
         *                              "entitiesString"). Empty when the graph
         *                              has no weights component or when
         *                              requesting nodes.
         *                              Supported values:
         *                              <ul>
         *                                  <li>@ref
         *                                      gpudb::get_graph_entities_true
         *                                      "get_graph_entities_true":
         *                                      Populate @ref
         *                                      gpudb::GetGraphEntitiesResponse::entitiesWeight
         *                                      "entitiesWeight" with per-edge
         *                                      weights (edge requests only).
         *                                  <li>@ref
         *                                      gpudb::get_graph_entities_false
         *                                      "get_graph_entities_false":
         *                                      Default: @ref
         *                                      gpudb::GetGraphEntitiesResponse::entitiesWeight
         *                                      "entitiesWeight" is empty.
         *                              </ul>
         *                              The default value is @ref
         *                              gpudb::get_graph_entities_false
         *                              "get_graph_entities_false".
         *                      </ul>
         *                      The default value is an empty map.
         */
        GetGraphEntitiesRequest(const std::string& graphName_, const int64_t offset_, const int64_t limit_, const std::map<std::string, std::string>& options_):
            graphName( graphName_ ),
            offset( offset_ ),
            limit( limit_ ),
            options( options_ )
        {
        }

        /**
         * Name of the graph from which to retrieve entities.
         */
        std::string graphName;

        /**
         * Starting index of the entities to retrieve (0-based). The default
         * value is 0.
         */
        int64_t offset;

        /**
         * Number of entities to retrieve starting from @ref offset. A value of
         * -1 returns all entities from the offset to the end. Note: the @ref
         * gpudb::GetGraphEntitiesResponse::entitiesInt "entitiesInt" or @ref
         * gpudb::GetGraphEntitiesResponse::entitiesString "entitiesString"
         * array size will be 2x this value for nodes (stride 2) or 4x for
         * edges (stride 4). The default value is 10000.
         */
        int64_t limit;

        /**
         * Optional parameters.
         * <ul>
         *     <li>@ref gpudb::get_graph_entities_entity_type
         *         "get_graph_entities_entity_type": The type of entity to
         *         retrieve.
         *         Supported values:
         *         <ul>
         *             <li>@ref gpudb::get_graph_entities_edge
         *                 "get_graph_entities_edge": Retrieve edge entities
         *                 (default).
         *             <li>@ref gpudb::get_graph_entities_node
         *                 "get_graph_entities_node": Retrieve node entities.
         *         </ul>
         *         The default value is @ref gpudb::get_graph_entities_edge
         *         "get_graph_entities_edge".
         *     <li>@ref gpudb::get_graph_entities_server_id
         *         "get_graph_entities_server_id": Indicates which graph server
         *         to send the request to. Required when the graph is
         *         distributed across multiple servers. The default value is
         *         '0'.
         *     <li>@ref gpudb::get_graph_entities_concise_edge_connectivity
         *         "get_graph_entities_concise_edge_connectivity": When true,
         *         edges are emitted in a compact connectivity form regardless
         *         of the graph's identifier type: @ref
         *         gpudb::GetGraphEntitiesResponse::entitiesInt "entitiesInt"
         *         contains stride-4 records [edge_id, node1_index,
         *         node2_index, edge_label_index] where node1_index/node2_index
         *         are 0-based positions into the node array (obtained from a
         *         node-entity call on the same graph). When requesting nodes
         *         with this option, the response includes tombstoned (deleted)
         *         slots in order to keep position indices stable so edge
         *         indices resolve correctly; deleted slots carry id=0 for
         *         integer graphs or an empty identifier for string/WKT graphs.
         *         For paginated node calls, subtract @ref offset from an edge
         *         endpoint index to locate it within the returned page.
         *         Supported values:
         *         <ul>
         *             <li>@ref gpudb::get_graph_entities_true
         *                 "get_graph_entities_true": Compact integer
         *                 connectivity for edges; deleted node slots included
         *                 in node output.
         *             <li>@ref gpudb::get_graph_entities_false
         *                 "get_graph_entities_false": Default: edges emit node
         *                 identifiers (int/string/WKT) matching the graph;
         *                 deleted nodes are skipped.
         *         </ul>
         *         The default value is @ref gpudb::get_graph_entities_false
         *         "get_graph_entities_false".
         *     <li>@ref gpudb::get_graph_entities_include_weights
         *         "get_graph_entities_include_weights": When true and @a
         *         options entityType is 'edge', the response @ref
         *         gpudb::GetGraphEntitiesResponse::entitiesWeight
         *         "entitiesWeight" array is populated with one float weight
         *         per emitted edge (aligned 1:1 with the edge records in @ref
         *         gpudb::GetGraphEntitiesResponse::entitiesInt "entitiesInt"
         *         or @ref gpudb::GetGraphEntitiesResponse::entitiesString
         *         "entitiesString"). Empty when the graph has no weights
         *         component or when requesting nodes.
         *         Supported values:
         *         <ul>
         *             <li>@ref gpudb::get_graph_entities_true
         *                 "get_graph_entities_true": Populate @ref
         *                 gpudb::GetGraphEntitiesResponse::entitiesWeight
         *                 "entitiesWeight" with per-edge weights (edge
         *                 requests only).
         *             <li>@ref gpudb::get_graph_entities_false
         *                 "get_graph_entities_false": Default: @ref
         *                 gpudb::GetGraphEntitiesResponse::entitiesWeight
         *                 "entitiesWeight" is empty.
         *         </ul>
         *         The default value is @ref gpudb::get_graph_entities_false
         *         "get_graph_entities_false".
         * </ul>
         * The default value is an empty map.
         */
        std::map<std::string, std::string> options;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::GetGraphEntitiesRequest>
    {
        static void encode(Encoder& e, const gpudb::GetGraphEntitiesRequest& v)
        {
            ::avro::encode(e, v.graphName);
            ::avro::encode(e, v.offset);
            ::avro::encode(e, v.limit);
            ::avro::encode(e, v.options);
        }

        static void decode(Decoder& d, gpudb::GetGraphEntitiesRequest& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.graphName);
                            break;

                        case 1:
                            ::avro::decode(d, v.offset);
                            break;

                        case 2:
                            ::avro::decode(d, v.limit);
                            break;

                        case 3:
                            ::avro::decode(d, v.options);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.graphName);
                ::avro::decode(d, v.offset);
                ::avro::decode(d, v.limit);
                ::avro::decode(d, v.options);
            }
        }
    };
} // end namespace avro

namespace gpudb
{
    /**
     * A set of results returned by @ref
     * GPUdb::getGraphEntities(const GetGraphEntitiesRequest&) const
     * "GPUdb::getGraphEntities".
     */
    struct GetGraphEntitiesResponse
    {
        /**
         * Constructs a GetGraphEntitiesResponse object with default
         * parameters.
         */
        GetGraphEntitiesResponse() :
            result(bool()),
            entitiesInt(std::vector<int64_t>()),
            entitiesString(std::vector<std::string>()),
            entitiesDouble(std::vector<double>()),
            entitiesWeight(std::vector<float>()),
            labels(std::vector<std::string>()),
            info(std::map<std::string, std::string>())
        {
        }

        /**
         * Indicates a successful retrieval.
         */
        bool result;

        /**
         * Flat array of entity data for integer-identifier graphs with a
         * repeating stride. For node entities (stride 2): [ node_id,
         * label_index, ...\ ]. For edge entities (stride 4): [ edge_id,
         * node1_id, node2_id, label_index, ...\ ]. Populated when the graph
         * uses integer identifiers; empty otherwise. The label_index is a
         * 1-based index into the @ref labels array; 0 indicates no label. When
         * the request option 'concise_edge_connectivity' is 'true', this array
         * is also used (regardless of graph identifier type) for edge entities
         * and carries [edge_id, node1_index, node2_index, edge_label_index]
         * where node1_index/node2_index are 0-based positions into the node
         * array returned from a paired node call on the same graph.
         */
        std::vector<int64_t> entitiesInt;

        /**
         * Flat array of entity data for name-identifier (string) graphs only.
         * For node entities (stride 2): [ node_name, label_index, ...\ ]. For
         * edge entities (stride 4): [ edge_id, node1_name, node2_name,
         * label_index, ...\ ]. Populated only when the graph uses string
         * identifiers. Empty for integer-identifier graphs (data goes to @ref
         * entitiesInt) and for WKT/geo-XY graphs (data always goes to @ref
         * entitiesDouble — 'POINT(x y)' strings are never emitted). The
         * label_index is a string representation of a 1-based index into the
         * @ref labels array; '0' indicates no label.
         */
        std::vector<std::string> entitiesString;

        /**
         * Compact double-packed payload for WKT (geo/XY) graphs. WKT graphs
         * ALWAYS use this array — 'POINT(x y)' strings are never emitted
         * anywhere. Stride 3 for nodes: [ x, y, label_index, ...\ ]. Stride 6
         * for edges (non-concise): [ edge_id, x0, y0, x1, y1, label_index,
         * ...\ ]. Empty for non-WKT graphs and when concise mode emits edges
         * into @ref entitiesInt instead. label_index/edge_id occupy double
         * slots (representable exactly up to 2^53). When
         * 'concise_edge_connectivity' is 'true' and entity_type is 'node',
         * tombstoned (deleted) WKT slots emit [0.0, 0.0, 0.0] to keep position
         * indices stable. Roughly 4x smaller on the wire than 'POINT(x y)'
         * strings and avoids any client-side regex parse.
         */
        std::vector<double> entitiesDouble;

        /**
         * Per-edge weight values, populated only when the request option
         * 'include_weights' is 'true' and @a options entityType is 'edge'.
         * Stride 1, aligned 1:1 with the edge records emitted in @ref
         * entitiesInt or @ref entitiesString (i.e.\ the i-th weight
         * corresponds to the i-th edge record). Empty when the graph has no
         * weights component, when requesting nodes, or when the option is not
         * set. Single-precision float matches the graph server's native weight
         * storage.
         */
        std::vector<float> entitiesWeight;

        /**
         * Array of distinct label strings. The label_index values in @ref
         * entitiesInt, @ref entitiesString, or @ref entitiesDouble are 1-based
         * indexes into this array; index 0 means no label.
         */
        std::vector<std::string> labels;

        /**
         * Additional information map. Contains the following keys:
         * 'identifier_type' — describes the graph's native node identifier
         * type: 'int', 'string', or 'wkt' (geo/XY graph). 'payload_type' —
         * describes which array actually holds this response payload: 'int'
         * (@ref entitiesInt), 'string' (@ref entitiesString), or 'double'
         * (@ref entitiesDouble). WKT graphs ALWAYS use 'double' for both nodes
         * and edges — 'POINT(x y)' strings are never emitted. In concise edge
         * mode payload_type is 'int' regardless of graph type. Clients should
         * dispatch on 'payload_type', not 'identifier_type', to parse the
         * response. 'total_count' — total number of entities available in the
         * graph for the requested entity_type, used for pagination; this is
         * the live (non-deleted) count by default, or the raw count (including
         * deleted slots) when 'concise_edge_connectivity' is true for a node
         * request. 'status_message' — set to 'Cancelled' if the request was
         * cancelled mid-iteration (with @ref result set to false).
         * 'concise_edge_connectivity' — set to 'true' when the response was
         * produced with the concise option (edges emitted as [edge_id,
         * v0_index, v1_index, label_idx] in @ref entitiesInt; WKT-graph nodes
         * emitted as [x, y, label_idx] in @ref entitiesDouble; non-WKT nodes
         * still in their native array; node output includes deleted slots to
         * keep indices stable). 'include_weights' — set to 'true' when @ref
         * entitiesWeight is populated.
         */
        std::map<std::string, std::string> info;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::GetGraphEntitiesResponse>
    {
        static void encode(Encoder& e, const gpudb::GetGraphEntitiesResponse& v)
        {
            ::avro::encode(e, v.result);
            ::avro::encode(e, v.entitiesInt);
            ::avro::encode(e, v.entitiesString);
            ::avro::encode(e, v.entitiesDouble);
            ::avro::encode(e, v.entitiesWeight);
            ::avro::encode(e, v.labels);
            ::avro::encode(e, v.info);
        }

        static void decode(Decoder& d, gpudb::GetGraphEntitiesResponse& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.result);
                            break;

                        case 1:
                            ::avro::decode(d, v.entitiesInt);
                            break;

                        case 2:
                            ::avro::decode(d, v.entitiesString);
                            break;

                        case 3:
                            ::avro::decode(d, v.entitiesDouble);
                            break;

                        case 4:
                            ::avro::decode(d, v.entitiesWeight);
                            break;

                        case 5:
                            ::avro::decode(d, v.labels);
                            break;

                        case 6:
                            ::avro::decode(d, v.info);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.result);
                ::avro::decode(d, v.entitiesInt);
                ::avro::decode(d, v.entitiesString);
                ::avro::decode(d, v.entitiesDouble);
                ::avro::decode(d, v.entitiesWeight);
                ::avro::decode(d, v.labels);
                ::avro::decode(d, v.info);
            }
        }
    };
} // end namespace avro

#endif // __GET_GRAPH_ENTITIES_H__
