/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */
#ifndef __SHOW_SYSTEM_STATUS_H__
#define __SHOW_SYSTEM_STATUS_H__

namespace gpudb
{
    /**
     * A set of parameters for @ref
     * GPUdb::showSystemStatus(const ShowSystemStatusRequest&) const
     * "GPUdb::showSystemStatus".
     *
     * Provides server configuration and health related status to the caller.
     * The admin tool uses it to present server related information to the
     * user.
     */
    struct ShowSystemStatusRequest
    {
        /**
         * Constructs a ShowSystemStatusRequest object with default parameters.
         */
        ShowSystemStatusRequest() :
            options(std::map<std::string, std::string>())
        {
        }

        /**
         * Constructs a ShowSystemStatusRequest object with the specified
         * parameters.
         *
         * @param[in] options_  Optional parameters, currently unused. The
         *                      default value is an empty map.
         */
        ShowSystemStatusRequest(const std::map<std::string, std::string>& options_):
            options( options_ )
        {
        }

        /**
         * Optional parameters, currently unused. The default value is an empty
         * map.
         */
        std::map<std::string, std::string> options;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::ShowSystemStatusRequest>
    {
        static void encode(Encoder& e, const gpudb::ShowSystemStatusRequest& v)
        {
            ::avro::encode(e, v.options);
        }

        static void decode(Decoder& d, gpudb::ShowSystemStatusRequest& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.options);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.options);
            }
        }
    };
} // end namespace avro

namespace gpudb
{
    /**
     * A set of results returned by @ref
     * GPUdb::showSystemStatus(const ShowSystemStatusRequest&) const
     * "GPUdb::showSystemStatus".
     */
    struct ShowSystemStatusResponse
    {
        /**
         * Constructs a ShowSystemStatusResponse object with default
         * parameters.
         */
        ShowSystemStatusResponse() :
            statusMap(std::map<std::string, std::string>()),
            info(std::map<std::string, std::string>())
        {
        }

        /**
         * A map of server configuration and health related status.
         */
        std::map<std::string, std::string> statusMap;

        /**
         * Additional information.
         */
        std::map<std::string, std::string> info;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::ShowSystemStatusResponse>
    {
        static void encode(Encoder& e, const gpudb::ShowSystemStatusResponse& v)
        {
            ::avro::encode(e, v.statusMap);
            ::avro::encode(e, v.info);
        }

        static void decode(Decoder& d, gpudb::ShowSystemStatusResponse& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.statusMap);
                            break;

                        case 1:
                            ::avro::decode(d, v.info);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.statusMap);
                ::avro::decode(d, v.info);
            }
        }
    };
} // end namespace avro

#endif // __SHOW_SYSTEM_STATUS_H__
