/*
 *  This file was autogenerated by the GPUdb schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */
#ifndef __SHOW_SYSTEM_PROPERTIES_H__
#define __SHOW_SYSTEM_PROPERTIES_H__

namespace gpudb
{

    /**
     * A set of input parameters for {@link
     * #showSystemProperties(const ShowSystemPropertiesRequest&) const}.
     * <p>
     * Returns server configuration and version related information to the
     * caller. The admin tool uses it to present server related information to
     * the user.
     */
    struct ShowSystemPropertiesRequest
    {

        /**
         * Constructs a ShowSystemPropertiesRequest object with default
         * parameter values.
         */
        ShowSystemPropertiesRequest() :
            options(std::map<std::string, std::string>())
        {
        }

        /**
         * Constructs a ShowSystemPropertiesRequest object with the specified
         * parameters.
         * 
         * @param[in] options_  Optional parameters.
         *                      <ul>
         *                              <li>
         *                      gpudb::show_system_properties_properties: A
         *                      list of comma separated names of properties
         *                      requested. If not specified, all properties
         *                      will be returned.
         *                      </ul>
         * 
         */
        ShowSystemPropertiesRequest(const std::map<std::string, std::string>& options_):
            options( options_ )
        {
        }

        std::map<std::string, std::string> options;
    };
}

namespace avro
{
    template<> struct codec_traits<gpudb::ShowSystemPropertiesRequest>
    {
        static void encode(Encoder& e, const gpudb::ShowSystemPropertiesRequest& v)
        {
            ::avro::encode(e, v.options);
        }

        static void decode(Decoder& d, gpudb::ShowSystemPropertiesRequest& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.options);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.options);
            }
        }
    };
}

namespace gpudb
{

    /**
     * A set of output parameters for {@link
     * #showSystemProperties(const ShowSystemPropertiesRequest&) const}.
     * <p>
     * Returns server configuration and version related information to the
     * caller. The admin tool uses it to present server related information to
     * the user.
     */
    struct ShowSystemPropertiesResponse
    {

        /**
         * Constructs a ShowSystemPropertiesResponse object with default
         * parameter values.
         */
        ShowSystemPropertiesResponse() :
            propertyMap(std::map<std::string, std::string>()),
            info(std::map<std::string, std::string>())
        {
        }

        std::map<std::string, std::string> propertyMap;
        std::map<std::string, std::string> info;
    };
}

namespace avro
{
    template<> struct codec_traits<gpudb::ShowSystemPropertiesResponse>
    {
        static void encode(Encoder& e, const gpudb::ShowSystemPropertiesResponse& v)
        {
            ::avro::encode(e, v.propertyMap);
            ::avro::encode(e, v.info);
        }

        static void decode(Decoder& d, gpudb::ShowSystemPropertiesResponse& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.propertyMap);
                            break;

                        case 1:
                            ::avro::decode(d, v.info);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.propertyMap);
                ::avro::decode(d, v.info);
            }
        }
    };
}

#endif
