/*
 *  This file was autogenerated by the Kinetica schema processor.
 *
 *  DO NOT EDIT DIRECTLY.
 */
#ifndef __VERIFY_BACKUP_H__
#define __VERIFY_BACKUP_H__

namespace gpudb
{
    /**
     * A set of parameters for @ref
     * GPUdb::verifyBackup(const VerifyBackupRequest&) const
     * "GPUdb::verifyBackup".
     *
     * Inspects the requested database <a
     * href="../../../admin/backup_restore/#database-backup"
     * target="_top">backup(s)</a> for conformity at the remote file store
     * accessible via the <a href="../../../concepts/data_sources/"
     * target="_top">data source</a> specified by @ref datasourceName. By
     * default all snapshots are inspected unless the option @ref
     * gpudb::verify_backup_backup_id "backup_id" is used to target a specific
     * instance.
     * Returns backup verification results.
     */
    struct VerifyBackupRequest
    {
        /**
         * Constructs a VerifyBackupRequest object with default parameters.
         */
        VerifyBackupRequest() :
            backupName(std::string()),
            datasourceName(std::string()),
            options(std::map<std::string, std::string>())
        {
        }

        /**
         * Constructs a VerifyBackupRequest object with the specified
         * parameters.
         *
         * @param[in] backupName_  Name of the backup. An empty string or '*'
         *                         will check all existing backups. Any text
         *                         followed by a '*' will inspect backups whose
         *                         name starts with that text. The default
         *                         value is ''.
         * @param[in] datasourceName_  Data source through which the backup is
         *                             accessible.
         * @param[in] options_  Optional parameters.
         *                      <ul>
         *                          <li>@ref gpudb::verify_backup_backup_id
         *                              "verify_backup_backup_id": ID of the
         *                              snapshot to verify. Set to '-1' to
         *                              verify all snapshots in the backup.
         *                              Leave empty to verify only the most
         *                              recent snapshot. The default value is
         *                              '-1'.
         *                      </ul>
         *                      The default value is an empty map.
         */
        VerifyBackupRequest(const std::string& backupName_, const std::string& datasourceName_, const std::map<std::string, std::string>& options_):
            backupName( backupName_ ),
            datasourceName( datasourceName_ ),
            options( options_ )
        {
        }

        /**
         * Name of the backup. An empty string or '*' will check all existing
         * backups. Any text followed by a '*' will inspect backups whose name
         * starts with that text. The default value is ''.
         */
        std::string backupName;

        /**
         * Data source through which the backup is accessible.
         */
        std::string datasourceName;

        /**
         * Optional parameters.
         * <ul>
         *     <li>@ref gpudb::verify_backup_backup_id
         *         "verify_backup_backup_id": ID of the snapshot to verify. Set
         *         to '-1' to verify all snapshots in the backup.  Leave empty
         *         to verify only the most recent snapshot. The default value
         *         is '-1'.
         * </ul>
         * The default value is an empty map.
         */
        std::map<std::string, std::string> options;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::VerifyBackupRequest>
    {
        static void encode(Encoder& e, const gpudb::VerifyBackupRequest& v)
        {
            ::avro::encode(e, v.backupName);
            ::avro::encode(e, v.datasourceName);
            ::avro::encode(e, v.options);
        }

        static void decode(Decoder& d, gpudb::VerifyBackupRequest& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.backupName);
                            break;

                        case 1:
                            ::avro::decode(d, v.datasourceName);
                            break;

                        case 2:
                            ::avro::decode(d, v.options);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.backupName);
                ::avro::decode(d, v.datasourceName);
                ::avro::decode(d, v.options);
            }
        }
    };
} // end namespace avro

namespace gpudb
{
    /**
     * A set of results returned by @ref
     * GPUdb::verifyBackup(const VerifyBackupRequest&) const
     * "GPUdb::verifyBackup".
     */
    struct VerifyBackupResponse
    {
        /**
         * Constructs a VerifyBackupResponse object with default parameters.
         */
        VerifyBackupResponse() :
            backupName(std::string()),
            backupNames(std::vector<std::string>()),
            backupIds(std::vector<std::vector<int64_t> >()),
            errors(std::vector<std::vector<std::string> >()),
            info(std::map<std::string, std::string>())
        {
        }

        /**
         * Value of @ref gpudb::VerifyBackupRequest::backupName "backupName".
         */
        std::string backupName;

        /**
         * Backup name(s).
         */
        std::vector<std::string> backupNames;

        /**
         * IDs of individual snapshots per backup name.
         */
        std::vector<std::vector<int64_t> > backupIds;

        /**
         * Any errors detected from the inspection of each backup.
         */
        std::vector<std::vector<std::string> > errors;

        /**
         * Additional information.
         */
        std::map<std::string, std::string> info;
    };
} // end namespace gpudb

namespace avro
{
    template<> struct codec_traits<gpudb::VerifyBackupResponse>
    {
        static void encode(Encoder& e, const gpudb::VerifyBackupResponse& v)
        {
            ::avro::encode(e, v.backupName);
            ::avro::encode(e, v.backupNames);
            ::avro::encode(e, v.backupIds);
            ::avro::encode(e, v.errors);
            ::avro::encode(e, v.info);
        }

        static void decode(Decoder& d, gpudb::VerifyBackupResponse& v)
        {
            if (::avro::ResolvingDecoder *rd = dynamic_cast< ::avro::ResolvingDecoder*>(&d))
            {
                const std::vector<size_t> fo = rd->fieldOrder();

                for (std::vector<size_t>::const_iterator it = fo.begin(); it != fo.end(); ++it)
                {
                    switch (*it)
                    {
                        case 0:
                            ::avro::decode(d, v.backupName);
                            break;

                        case 1:
                            ::avro::decode(d, v.backupNames);
                            break;

                        case 2:
                            ::avro::decode(d, v.backupIds);
                            break;

                        case 3:
                            ::avro::decode(d, v.errors);
                            break;

                        case 4:
                            ::avro::decode(d, v.info);
                            break;

                        default:
                            break;
                    }
                }
            }
            else
            {
                ::avro::decode(d, v.backupName);
                ::avro::decode(d, v.backupNames);
                ::avro::decode(d, v.backupIds);
                ::avro::decode(d, v.errors);
                ::avro::decode(d, v.info);
            }
        }
    };
} // end namespace avro

#endif // __VERIFY_BACKUP_H__
